// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel1API.Models;

namespace Travel1API.Migrations
{
    [DbContext(typeof(Travel1APIContext))]
    [Migration("20220831060458_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Travel1API.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            DestinationName = "London"
                        },
                        new
                        {
                            DestinationId = 2,
                            DestinationName = "Algeria"
                        },
                        new
                        {
                            DestinationId = 3,
                            DestinationName = "Australia"
                        },
                        new
                        {
                            DestinationId = 4,
                            DestinationName = "Chicago"
                        },
                        new
                        {
                            DestinationId = 5,
                            DestinationName = "Los Angeles"
                        });
                });

            modelBuilder.Entity("Travel1API.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Description = "Bad roads",
                            DestinationId = 2,
                            Rating = 2
                        },
                        new
                        {
                            ReviewId = 2,
                            Description = "Tasty food",
                            DestinationId = 1,
                            Rating = 3
                        },
                        new
                        {
                            ReviewId = 3,
                            Description = "Fast policia",
                            DestinationId = 3,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 4,
                            Description = "Expensive taxi",
                            DestinationId = 4,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 5,
                            Description = "Danger neighborhood",
                            DestinationId = 5,
                            Rating = 4
                        });
                });

            modelBuilder.Entity("Travel1API.Review", b =>
                {
                    b.HasOne("Travel1API.Destination", null)
                        .WithMany("Reviews")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Travel1API.Destination", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
